### PR TITLE
navbar

### PR DESCRIPTION
**Pull request by mitchellblom**
## Status
Choose:
**READY**

## Description
Adds a navbar to the app to view our models. Easy peezy.

## Todos
- [ ] Tests
- [ ] Documentation

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.
1. git fetch
2. git checkout ...
3. build and view
4. test links

## Impacted Areas in Application
List general components of the application that this PR will affect:
Every page view will now have a link to every other view

## Link to Feature Ticket
#32 
@ill-fated-ducks

### CODE REVIEW

**Comment by jordandhaenens** [comment]
Works flawlessly

**Comment by azimsodikov** [comment]
👍 Ready to merge

**Comment by mitchellblom** [comment]
@ill-fated-ducks please test this again. Edited a couple ComputerEmployee dates and added another Computer. Also @azimsodikov were you up at 4am?!?!

**Comment by azimsodikov** [comment]
Navbar works just fine, Also I see changed files and looks like there are more than navbar

**Comment by arock83** [comment]
👍 fixed the merge conflict should be good to go

**Pull request merged**
