### PR TITLE
Az fix

### PR DESCRIPTION
**Pull request by azimsodikov**
## Status
Choose:
**READY**

## Description
So I removed the project and cloned again, removed migrations, views and scaffolded again, after fixing some methods on seedData, it is populating the tables without exceptions. It seems it is working fine.
**Checkout to my branch and just try to build it but make sure your tables are empty** 

## Todos
- [ ] Tests

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.
1. git fetch
2. git checkout az-fix
3.  clean up the tables in your db
4.  build it 
5. It should populate all the tables

## Impacted Areas in Application
Everything 

## Link to Feature Ticket
#34 #33 #31 
@ill-fated-ducks

### CODE REVIEW

**Comment by mitchellblom** [comment]
@azimsodikov I pulled it into a test branch and upon build there's a `SqlException: Invalid column name 'Description'.` Did you come across that on your build?

**Comment by mitchellblom** [comment]
Seed data ID linqs look gooooood

**Comment by azimsodikov** [comment]
@mitchellblom thats because I added description column which you do not have in your database, try to update your database first, once it is then try to seed

**Comment by azimsodikov** [comment]
Sorry I forgot to mention it on PR

**Comment by cleverbek1991** [comment]
I just tested 👍  after updating database it worked.

**Pull request merged**
